### ISSUE TITLE
SVG Exports change the font

### ISSUE THREAD

**Issue by AABoyles** [CDCgov/MicrobeTrace#110]
The default font is a serif font, but MicrobeTrace's font-family is
```CSS
body {
  font-family: -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,"Noto Sans",sans-serif,"Apple Color Emoji","Segoe UI Emoji","Segoe UI Symbol","Noto Color Emoji";
}
```
Let's make sure to insert the default font-family in the [Stylesheet that gets built for the SVG](https://github.com/CDCgov/MicrobeTrace/blob/master/scripts/common.js#L864).
